image:
  - Visual Studio 2017
  - Visual Studio 2015
environment:
  CIRCLE_TOKEN:
    secure: TQKcepXmTzCNt4+tUBtYpwEQkdSPwFr9A8ugtoMhNbKu/SW1WM1EpjEu6kYXxpQ4
  TRAVIS_TOKEN:
    secure: tR7HXYv3x97q90uvPrjUxKZh7R1+uqKct0HdEcqTbsg=
  GITHUB_TOKEN:
    secure: 3wuEGJsppSKFvdwhp3jprUA9Zkc3WINlc/9oFXjhAR6J05lYMXP7Fl7lXTKpkGZx
install:
  - ps: Install-Product node 8
  - curl -L -o nasm.exe https://www.nasm.us/pub/nasm/releasebuilds/2.13.03/win64/nasm-2.13.03-installer-x64.exe
  - start /wait nasm.exe /S
  - ps: $env:path="C:\Program Files\nasm;$($env:path)"
  - yarn
build: off
test: off
build_script:
  - yarn run asset-compile
artifacts:
  - path: $(HOMEPATH)\.nexe\**\node.exe
