jobs:
- job: BaseBuild
  timeoutInMinutes: 0
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-16.04'
      mac:
        imageName: 'macos-10.13'
      windows_2017:
        imageName: 'vs2017-win2016'
      windows_2015:
        imageName: 'vs2017-win2016'
      alpine:
        imageName: 'ubuntu-16.04'
  pool:
    vmImage: $(imageName)
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.7'
      architecture: 'x64'
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
  - script: sudo apt-get install -y libc6-dev-i386 gcc-multilib g++-multilib
    condition: eq(variables['Agent.JobName'], 'linux')
    displayName: Install Linux Build Dependencies
  - script: choco install visualcpp-build-tools --version 14.0.25420.1 -fy && npm config set msvs_version 2015
    condition: startsWith(variables['Agent.JobName'], 'windows_2015')
    displayName: Install Windows Build Dependencies
  - script: choco install nasm -fy --dir nasm && cd nasm && dir
    condition: startsWith(variables['Agent.JobName'], 'windows')
    displayName: Install Windows Assembler
  - script: echo '##vso[task.prependpath]%AGENT_BUILDDIRECTORY%\nasm' && nasm -v
    condition: startsWith(variables['Agent.JobName'], 'windows')
    displayName: Add Windows Assembler to PATH
  - script: npm install && npm run ci:build
    displayName: Install dependencies and build base binaries...
    env:
      GITHUB_TOKEN: $(PersonalGithubToken)
