version: 2

jobs:
  build:
    macos:
      xcode: "9.0"
    steps:
    - checkout
    - restore_cache:
        keys:
        - package-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
        - package- # Fallback for the latest package.json cache
    - run:
        name: setup
        command: .circleci/setup.sh
    - save_cache:
        key: package-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }} 
        paths:
        - node_modules
    - run:
        name: build
        command: .circleci/build.sh

workflows:
  version: 2
  test:
    jobs:
      - build
